### ISSUE TITLE
[Suggestion] Arrows instead of blobs

### ISSUE THREAD

**Issue by SkilledAlpaca** [ideka/AugTyr#11]
So after playing around with this for a couple quick maps, when you Way Point sometimes orienting yourself is a bit of a pain. Maybe you could do triangle blobs for things you need to get and regular flat triangles for just directions?

**Comment by ideka** [comment]
I think follow mode already solves this problem. Have you used it? [More info here](https://www.reddit.com/r/AugmentedTyria/comments/6oxyhu/augmented_tyria_release_02beta/).

**Comment by SkilledAlpaca** [comment]
Period is toggling the lines on and off. How exactly should follow mode work?

**Comment by ideka** [comment]
> Period is toggling the lines on and off.

Nope, that's not correct. *Most* of the line dissapears because you're never gonna really need to look at the *entire* thing to know where to go next.

Try changing to follow mode (Numpad .), then selecting the closest node (Numpad 5). Also you might want to turn on the orientation helper (Numpad 0).
