### ISSUE TITLE
[Suggestion] Follow-mode should be default.

### ISSUE THREAD

**Issue by ghost** [ideka/AugTyr#13]
As title reads, the option for the green line to closest node should in my opinion also always be on for ease of use.

**Comment by ideka** [comment]
I decided edit mode should be default because it can otherwise be confusing for people who come back to a map they previously left half-done.

The default could be made selectable via a UserConfig option though. But the *default* default I think should be edit mode.

As for the orientation helper (the green line), I'm already planning on making it on by default. Users that wish for there not to even be a key to turn it off can remove the UserConfig keybinding.

**Comment by ideka** [comment]
Dealt with in dca041c0d24464ab569114598e55ff738f8d0219.
