### ISSUE TITLE
New "mode"

### ISSUE THREAD

**Issue by TicWE** [ideka/AugTyr#23]
What about a mode that creates a route based on your deplacements ? I don't know if this is possible but would be really amazing, something that would place nodes every x meters (we could obviously add some by ourselves), well I let you think about it ;)

**Comment by ideka** [comment]
Like a setting that automatically places a node whenever you're far away enough from the last placed node?

How would that be useful?

**Comment by TicWE** [comment]
Could be useful to create new routes with having to use "+" all the time, and would also be a time saver

**Comment by ideka** [comment]
The distance to the previous node doesn't play a part in determining if a new node should be placed. I.e. you should never place a new node only because you've determined that the previous node is too far.

A setting to intelligenty place nodes automatically could be good and useful if properly thought of and implemented, but it would not be based on distance.

**Comment by TicWE** [comment]
Maybe whenever the player changes of direction, jumps, things like that ?

**Comment by ideka** [comment]
Well, the mumble API dosen't exactly report on direction changes or jumps, only position.

I could maybe code an "educated guess algorithm," e.g. if the vertical position went up a certain amount in a certain amount of time, then the player *probably* jumped.

Even then, doesn't sound useful to me. I make routes way more meticulously than just running through a map pressing + every so often, and I hope other people do as well.
